[[has-child]]
=== 根据子文档查询父文档

`has_child` 的 query 和 filter 可以根据子文档的内容来查询父文档。((("has_child query and filter")))((("parent-child relationship", "finding parents by their children")))例如，我们根据如下查询，可查出所有出生在1980年之后的雇员所在的公司：
[source,json]
-------------------------
GET /company/branch/_search
{
  "query": {
    "has_child": {
      "type": "employee",
      "query": {
        "range": {
          "dob": {
            "gte": "1980-01-01"
          }
        }
      }
    }
  }
}
-------------------------

`has_child` query 和 <<nested-query,`nested` query>> 类似，查询返回的结果都可以包括多个子文档((("has_child query and filter", "query")))，并且每一个子文档的评分值都不同。但是由于每一个子文档都带有评分，因此父文档的评分需要取决于 `score_mode` 这个参数。该参数有多种取值策略：默认为 `none` ，会忽略子文档的评分，并且会给父文档评分设置为 `1.0` ；
还可以设置成 `avg` 、 `min` 、 `max` 和 `sum` 。

下面的查询将会返回 `london` 和 `liverpool` 。由于 `Alice Smith` 要比 `Barry Smith` 更加匹配查询条件，因此 `london` 会得到一个更高的评分。

[source,json]
-------------------------
GET /company/branch/_search
{
  "query": {
    "has_child": {
      "type":       "employee",
      "score_mode": "max",
      "query": {
        "match": {
          "name": "Alice Smith"
        }
      }
    }
  }
}
-------------------------

TIP: `score_mode` 为默认的 `none` 时，会显著地比其模式要快，这是因为Elasticsearch不需要计算每一个子文档的评分。只有当你真正需要关心评分结果时，才需要为 `source_mode` 设值，例如设成 `avg` 、 `min` 、 `max` 或 `sum` 。((("parent-child relationship", "finding parents by their children", "min_children and max_children")))

[[min-max-children]]
==== min_children 和 max_children

`has_child` 的 query 和 filter 都可以传这两个参数：`min_children` 和 `max_children` 。 ((("min_children parameter")))((("max_children parameter")))((("has_child query and filter", "min_children or max_children parameters"))) 使用这两个参数时，只有当父文档的子文档数量大于 `min_children` 或者小于 `max_children` 时，才会返回父文档。

如下查询只会返回至少有两个雇员的分公司：

[source,json]
-------------------------
GET /company/branch/_search
{
  "query": {
    "has_child": {
      "type":         "employee",
      "min_children": 2, <1>
      "query": {
        "match_all": {}
      }
    }
  }
}
-------------------------
<1> 至少有两个雇员的分公司才会符合查询条件。

带有 `has_child` 、 `min_children` 和 `max_children` 参数的 query 或者 filter，在性能上都没有显著差异。

.has_child Filter
**************************

`has_child` filter 和 `has_child` query 在运行机制上类似，((("has_child query and filter", "filter")))区别是 `has_child` filter 不支持 `source_mode` 参数。`has_child` filter 只可以用在 filter 的上下文中（例如在 `filtered` query 中）并且和其他任何的 filter 一样：结果存在，或者不存在，并且没有评分机制。

`has_child` filter 本身的结果不可被缓存，但是其内部 filter 的结果是可以被缓存的。
**************************
